version: 2
updates:

  # Security updates for Go backend (does NOT update versions)
  - package-ecosystem: "gomod"
    directory: "/src/backend"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "[dependabot-security]"
    open-pull-requests-limit: 1
    groups:
      backend-dependencies:
        patterns:
          - "*"
