renovate:
  stage: test
  image: renovate/renovate:latest
  variables:
    RENOVATE_TOKEN: $GITLAB_API_TOKEN
    RENOVATE_PLATFORM: "gitlab"
    RENOVATE_ENDPOINT: $CI_API_V4_URL
    RENOVATE_REPOSITORIES: $CI_PROJECT_PATH
    RENOVATE_CONFIG_FILE: renovate.json
    LOG_LEVEL: "info"
  script:
    - renovate
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: always
    - if: $CI_PIPELINE_SOURCE == "web"
      when: manual